# Aprovisionamiento automático del origen de datos InfluxDB para Grafana.
# Grafana lo carga al arrancar: no hay que configurarlo a mano por la interfaz.
apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb_sensores
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: ujaen
      defaultBucket: sensores_bucket
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token
    editable: true
